### PR TITLE
Added an endpoint for question controller

### PR DESCRIPTION
**Pull request by mattfreshwaters**
Getting a list of questions by the item family (methods all work and already tested for)

### CODE REVIEW

**Review by jaitken — APPROVED** [review]
looks good

**Review by neveland98 — CHANGES_REQUESTED** [review]
This looks fine, I would just add some kind of error handling to this in case of the wrong itemFamilyId being passed to it, I just tested it and it seems like it returns nothing in that case, but it should throw some kind of exception.

**Comment by mattfreshwaters** [comment]
> This looks fine, I would just add some kind of error handling to this in case of the wrong itemFamilyId being passed to it, I just tested it and it seems like it returns nothing in that case, but it should throw some kind of exception.

Good suggestion, I'll add some handling then push it

**Review by neveland98 — APPROVED** [review]
Looks good, just make sure you write some unit tests as well if you haven't already :)

**Pull request merged**
