### PR TITLE
integrate the related bought items component into main backend application

### PR DESCRIPTION
**Pull request by timluu**
This PR adds in the Related Bought Items component of the application into backend. Many-to-many table introduced in the Items model to create the relation of bought items. Also includes minor fixes to misc configuration files.

### CODE REVIEW

**Review by mattfreshwaters — APPROVED** [review]
Looks good, good idea using set for relatedBoughtItems

**Review by jaitken — APPROVED** [review]
Looks good, at first it was a little hard to wrap my head around the difference between relatedBoughtItems and boughtItems sets in the Item model so maybe you want to add some comments. Good work!

**Comment by timluu** [comment]
> Looks good, at first it was a little hard to wrap my head around the difference between relatedBoughtItems and boughtItems sets in the Item model so maybe you want to add some comments. Good work!

@jaitken good point. tbh, i was a bit iffy on the naming actually since i don't think it's very clear, so i'm glad you pointed that out too. thoughts on other naming choices? i might just go with "items" and "itemId" but just wanna make sure it doesn't get confused since the join table lives inside the Items model. tagging @mattfreshwaters in case you have any thoughts on this too

**Comment by jaitken** [comment]
hmm also a good point. If not just "items" maybe "relatedItems"

**Comment by mattfreshwaters** [comment]
> > Looks good, at first it was a little hard to wrap my head around the difference between relatedBoughtItems and boughtItems sets in the Item model so maybe you want to add some comments. Good work!
> 
> @jaitken good point. tbh, i was a bit iffy on the naming actually since i don't think it's very clear, so i'm glad you pointed that out too. thoughts on other naming choices? i might just go with "items" and "itemId" but just wanna make sure it doesn't get confused since the join table lives inside the Items model. tagging @mattfreshwaters in case you have any thoughts on this too

Yeah I think mainly changing the boughtItems would help, I understood what you were going for but if I someone coming in from the outside I would probably be confused.  The relatedBoughtItems is fine but if you're going to rename boughtItems I think it makes sense to change both

**Comment by jaitken** [comment]
I might have a misunderstanding of how the many to many is working though, you probably have a better grasp of whats happening than I do.

**Pull request merged**
